Helendeweser/rails-natuurbuur

Gemfile.lock
app/views/layouts/application.html.erb

Add of a container class on the whole body in app.html.erb

Container on app scss

---

Gemfile.lock
app/assets/stylesheets/components/_form.scss
app/views/pages/testing.html.erb

form in progress...need experiences controller for testing

form in progress...(need experiences controller)

---

app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/config/_fonts.scss

fonts and colors shared

---

app/controllers/application_controller.rb
app/models/user.rb
app/views/devise/registrations/new.html.erb
db/migrate/20230307112616_add_username_to_user.rb
db/schema.rb

not finish yet but username is available

username for users done

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_small_card.scss
app/views/pages/testing.html.erb

small cards waiting for content (seed)

small cards layout done waiting content

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_index.scss
app/views/pages/testing.html.erb

check out my footer component pls :)

footer component done

---

app/assets/stylesheets/components/_form_button.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_rounded_pictures.scss
app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb
app/views/solutions/index.html.erb

button, picture rounded, fonts

button, pic, fonts

---

app/assets/stylesheets/components/_form_button.scss
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb

buttons on the forms placed and fixed
fe25c2d5649b.png">

buttons on the forms set and fixed

---

app/assets/stylesheets/components/_show_image.scss
app/assets/stylesheets/config/_colors.scss
app/views/solutions/show.html.erb

Show page done only waiting for icons

show page almost done, waiting for icons

---

app/assets/stylesheets/components/_cards_index.scss
app/assets/stylesheets/pages/_index.scss
app/controllers/dashboards_controller.rb
app/views/dashboards/my_solutions.html.erb
app/views/solutions/index.html.erb

dashboard view

---

app/views/layouts/application.html.erb

mise a jour footer

---

app/assets/stylesheets/components/_form.scss
app/assets/stylesheets/components/_show_card.scss
app/assets/stylesheets/components/_show_image.scss
app/controllers/experiences_controller.rb
app/controllers/solutions_controller.rb
app/models/experience.rb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/pages/testing.html.erb
app/views/solutions/show.html.erb

We are able to write a review and it's displaying review + rating. styling still has to be refined

reviews done

---

app/assets/stylesheets/components/_homepage_searchbar.scss
app/assets/stylesheets/components/_navbar.scss
app/views/layouts/application.html.erb
app/views/shared/_homepage_searchbar.erb
app/views/solutions/index.html.erb

banner recententered see application html

banner recentered

---

app/models/solution.rb
app/views/solutions/_card.html.erb
app/views/solutions/show.html.erb
db/seeds.rb

changed images

---

app/assets/stylesheets/components/_formbutton.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_show_image.scss
app/assets/stylesheets/components/_small_card.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/config/_colors.scss

Tesing colorss (merge pas encore, on va voir demain)

---

app/views/shared/_homepage_searchbar.erb
app/views/shared/_navbar.html.erb

moving the title higher and wider navbar

moving the title higher and wider navbar

---

app/assets/stylesheets/components/_show_card.scss
app/views/solutions/show.html.erb

(username still need to b…e displayed)

add experiences with or without photos done 

---

app/javascript/application.js
app/javascript/controllers/index.js
app/javascript/controllers/tooltip_controller.js
app/views/solutions/_advantages_show_card.html.erb
package.json
yarn.lock

hover over logo

---

app/assets/stylesheets/components/_formbutton.scss
app/assets/stylesheets/components/_show_card.scss
app/views/solutions/show.html.erb

reviews are displaying nicely even if there is no image. please try on your computers to see if it's ok or still need fixes. Thanks

display reviews corrected

---

app/models/solution.rb

added dependent destroy for likes

so that we can re seed

---

app/assets/stylesheets/components/_index.scss
app/javascript/controllers/create_experience_controller.js
app/views/solutions/_experience.html.erb
app/views/solutions/show.html.erb

message if there is no reviews yet and username displayed

---

app/assets/stylesheets/components/_show_card.scss
app/controllers/experiences_controller.rb
app/javascript/controllers/create_experience_controller.js
app/views/solutions/_experience.html.erb
app/views/solutions/show.html.erb

delete experience done and you can only can delete your own experience

---

db/seeds.rb

added some seeds (pas bcp, on doit encore mettre plus si on a le temps)

---

app/views/solutions/_experience.html.erb

peut etre dangereux review size

---

app/assets/stylesheets/components/_big_image.scss
app/assets/stylesheets/components/_cards_index.scss
app/assets/stylesheets/components/_cards_map.scss
app/assets/stylesheets/components/_small_card.scss
app/views/solutions/index.html.erb

index page fixed

---

app/assets/stylesheets/components/_advantage_image.scss
app/assets/stylesheets/components/_show_card.scss
app/assets/stylesheets/components/_show_image.scss
app/assets/stylesheets/components/_small_card.scss
app/views/dashboards/my_solutions.html.erb
app/views/layouts/application.html.erb
app/views/solutions/index.html.erb
app/views/solutions/show.html.erb

show changed
